### ISSUE TITLE
error reading input csvs

### ISSUE THREAD

**Issue by alisonmyers** [saud-learning-services/quiz-extension#8]
Error finding files in input (maybe a windows/mac difference - I don't think mac allows \\ in paths)

Same error occurs when created files in input called quiz_input and student_input
Same error when select to not create inputs 

```
For first time use on a machine, the following two steps are mandatory.

Do you want to create a Quiz List CSV to edit as input (Y/N): Y
Traceback (most recent call last):
  File "src/extend_quiz.py", line 200, in <module>
    extend_quiz_a()
  File "src/extend_quiz.py", line 158, in extend_quiz_a
    dl_quizzes(course)
  File "src/extend_quiz.py", line 89, in dl_quizzes
    df.to_csv(path, index=False)
  File "/anaconda3/envs/QE_env/lib/python3.8/site-packages/pandas/core/generic.py", line 3167, in to_csv
    formatter.save()
  File "/anaconda3/envs/QE_env/lib/python3.8/site-packages/pandas/io/formats/csvs.py", line 185, in save
    f, handles = get_handle(
  File "/anaconda3/envs/QE_env/lib/python3.8/site-packages/pandas/io/common.py", line 493, in get_handle
    f = open(path_or_buf, mode, encoding=encoding, errors=errors, newline="")
FileNotFoundError: [Errno 2] No such file or directory: '/Users/al2myers/Documents/GitHub/Sauder_Learning_Services/quiz-extension\\src\\input/quiz_input.csv'
```

**Comment by JeremyH011** [comment]
I changed the file paths from using \\ to /, I wasn't aware mac made a difference. Sorry. 
Please give it a try.
